version: '2'
services:
  firefox:
    container_name: selenium-firefox-container
    image: selenium/node-firefox:3.12.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  
  chrome:
    container_name: selenium-chrome-container
    image: selenium/node-chrome:3.12.0-americium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    container_name: selenium-hub
    image: selenium/hub:3.12.0-americium
    ports:
      - "4444:4444"

  ebaytest:
    container_name: ebayTest
    image: kinglu/ebaytest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
      - firefox
      - chrome
